# Generated by Django 5.2.13 on 2026-05-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_completed_trips',
            field=models.IntegerField(default=0, verbose_name='Завершённых поездок'),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_level',
            field=models.IntegerField(default=1, verbose_name='Уровень доверия (1-10)'),
        ),
    ]
