# Generated by Django 5.2.13 on 2026-05-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_total_completed_trips_user_trust_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='Доступ в админку'),
        ),
    ]
