# Generated by Django 5.2.13 on 2026-05-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0012_routecomment_routelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='max_spots',
            field=models.PositiveIntegerField(default=6, verbose_name='Всего мест'),
        ),
    ]
